# This file lists the dependencies needed to build and test all of pyflatsurf.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
# conda env update -n pyflatsurf-build -f environment.yml
name: pyflatsurf-build
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - automake
  # The latest cppyy has trouble with serializations, see https://bitbucket.org/wlav/cppyy/issues/364/segfault-in-clang-cxxrecorddecl
  - cppyy<2
  - cppyythonizations
  - gmpxxyy
  - ipywidgets
  - libtool
  - make
  - pyexactreal>=2.0.0,<3
  - pytest
  - python
  - sagelib
  - setuptools
  - sympy
