# This file lists the dependencies needed to build and test all of pyflatsurf.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
# conda env update -n pyflatsurf-build -f environment.yml
name: pyflatsurf-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - cppyy
  - cppyythonizations >=1.2.2,<2
  - gmpxxyy
  - ipywidgets
  - libtool
  - make
  - pyintervalxt>=3.2.0,<4
  - pyexactreal>=3.0.1,<5
  - pytest
  - python
  - sagelib
  - setuptools
  - sympy
