# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set component = component or 'flatsurf' %}
{% set action = action or 'release' %}

package:
  name: {{ component }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
{%- if component in ["libflatsurf", "flatsurf-polygon"] %}
  string: {{ build_number }}
{%- else %}
  string: py{{ _python | replace('*', '') | replace(' ', '') | replace('.', '') }}_{{ build_number }}
{%- endif %}
  # intervalxt is not available on Windows yet
  skip: True  # [win]
  # intervalxt is not available on macOS yet
  skip: True  # [osx]
  # we do not support old versions of Python
  skip: True  # [py < 36]
{%- if component == "libflatsurf" %}
  run_exports:
    # We pin the version of libflatsurf exactly since we do not want to
    # bother with incompatibilities in our nightly builds.
    - {{ pin_subpackage(component, exact=True) }}
{%- endif %}
  script_env:
    - CODECOV_TOKEN
    - ASV_SECRET_KEY

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
{%- if action == "benchmark" %}
    - git
{%- elif action == "style" %}
    - clangdev ==8.0.0
{%- endif %}
  host:
{%- if component in ["flatsurf", "libflatsurf"] %}
    - arb
    - boost-cpp
    - libintervalxt
    - libexactreal
    - e-antic 1.*
    - gmp
    - fmt
{%- endif %}
{%- if component in ["flatsurf", "pyflatsurf"] %}
    - python {{ _python }}
    - setuptools
    - pyexactreal
    - cppyythonizations
{%- endif %}
{%- if component in ["flatsurf", "flatsurf-polygon"] %}
    - arb
    - boost-cpp
    - libexactreal
    - libintervalxt
    - e-antic 1.*
    - gmp
    - ntl
    - eigen
{%- endif %}
{%- if component in ["pyflatsurf", "flatsurf-polygon"] %}
    - libflatsurf {{ version }} {{ build_number }}
{%- endif %}
{%- if action in ["test", "coverage", "benchmark"] %}
    # enable test/pyflatsurf tests in ./configure
    - pytest
    - cppyy
    # make sage-flatsurf integration doctests pass
    - sage-flatsurf
    - sagelib
    - pip
    - ipywidgets
    - sympy
    # enable test/libflatsurf tests in ./configure
    - benchmark
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0
{%- endif %}
{%- if action == "benchmark" %}
    # requirements for ASV benchmarks
    - asv
{%- endif %}
  run:
{%- if component == "libflatsurf" %}
    # fmt is missing a run_exports rule, see https://github.com/conda-forge/fmt-feedstock/pull/11
    - fmt
{%- endif %}
{%- if component == "pyflatsurf" %}
    - python {{ _python }}
    - cppyy
    - pyexactreal
    - boost-cpp
    - cppyythonizations
{%- endif %}

outputs:
  - name: {{ component }}
{%- if action == "release" %}
    script: install-{{ component }}.sh
{%- endif %}
{%- if component == "pyflatsurf" %}
    test:
      imports:
        - {{ component }}
{%- endif %}
{%- if component == "flatsurf-polygon" %}
    test:
      commands:
        - flatsurf-polygon 1 2 2 1
{%- endif %}

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL3
  license_file: COPYING
  summary: TBD

extra:
  recipe-maintainers:
    - saraedum
    - videlec
  variables:
    action: {{ action }}
    job: {{ job }}
    component: {{ component }}
