# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set version = environ.get('GIT_DESCRIBE_TAG')|string %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + build_number %}

package:
  name: polygon
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  skip: true    # [win]

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - gmp
    - ntl
    - boost-cpp

# Currently, conda-build does not run the test section when it is output-specific
# Of course, this should go to the polygon output only. Likely this is going to work
# again with a newer version of conda-build.
test:
  source_files:
    - asv.conf.json 
    - test/
    - recipe/asv-machine.json
  commands:
    - cp recipe/asv-machine.json ~/.asv-machine.json
    - test/run.sh --machine=circleci                # [linux]
    # Tests on macOS fail at the moment. It's unclear whether that's a problem, see https://github.com/polygon-tbd/polygon/pull/5
    - test/run.sh --machine=circleci || true        # [osx]
  requires:
    - asv
    # can be removed once https://github.com/conda-forge/asv-feedstock/pull/10 has been resolved
    - setuptools

outputs:
  - name: libpolygon
    build:
      run_exports:
        - {{ pin_subpackage("libpolygon", exact=True) }}
    files:
      - lib/*.dylib    # [osx]
      - lib/*.so*      # [linux]
      - include/libpolygon/*.h
  - name: polygon
    requirements:
      run:
        - {{ pin_subpackage('libpolygon', exact=True) }}
    files:
      - bin/polygon

about:
  home: https://github.com/polygon-tbd/polygon
  license: GPL2
  license_file: COPYING
  summary: Alex Eskin's polygon program

extra:
  recipe-maintainers:
    - saraedum
