{% set version = "0.0.1" %}
{% set name = "polygon" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

# TODO: run_exports once this is a library
# TODO: Do we want a coverage variant?

build:
  number: 0
  skip: true        # [win or osx]

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - gmp
    - ntl
    - boost-cpp

test:
  source_files:
    - test/
  commands:
    - test/run.sh

about:
  home: https://github.com/polygon-tbd/polygon
  license: GPL2
  license_file: COPYING
  summary: Alex Eskin's polygon program

extra:
  recipe-maintainers:
    - saraedum
