# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + build_number %}
{% set flavour = environ.get('FLAVOUR', 'build')|string %}

package:
  name: flatsurf
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # currently not built for Windows & macOS
  skip: True  # [win]
  skip: True  # [osx]
  script:
    - source ./recipe/cflags.sh
    - source /tmp/secrets
    - ./recipe/build-{{ flavour }}.sh
    - ./recipe/test-{{ flavour }}.sh
    - make install

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - boost-cpp
    - libexactreal
    - e-antic 1.*
    - arb
    - gmp
    - mpfr
    - ntl
    # requirement of make check which also runs benchmarks
    - gtest
    - benchmark

outputs:
  - name: libflatsurf
    build:
      run_exports:
        - {{ pin_subpackage("libflatsurf", exact=True) }}
    files:
      - lib/*.dylib    # [osx]
      - lib/*.so*      # [linux]
      - include/flatsurf/*.h
  - name: flatsurf
    requirements:
      run:
        - {{ pin_subpackage("libflatsurf", exact=True) }}
      files:
        - bin/flatsurf

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL2
  license_file: COPYING
  summary: Alex Eskin's polygon program


extra:
  recipe-maintainers:
    - saraedum
    - videlec
