# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set name = name or 'flatsurf' %}
{% set target = target or 'release' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
{%- if target == "release" %}
{%- if name in ["libflatsurf", "flatsurf-polygon"] %}
  string: {{ build_number }}
{%- else %}
  string: py{{ python }}_{{ build_number }}
{%- endif %}
{%- else %}
  string: {{ target }}
{%- endif %}
  # intervalxt is not available on Windows yet
  skip: True  # [win]
  # intervalxt is not available on macOS yet
  skip: True  # [osx]
  # we do not support old versions of Python
  skip: True  # [py < 36]
{%- if name != "pyflatsurf" and target != "test" %}
  # ignore Python version where it does not matter (conda-smithy still renders these but conda-build stops immediately)
  skip: True  # [py != 37]
{%- endif %}
{%- if name == "libflatsurf" %}
  run_exports:
    # We pin the version of libflatsurf exactly since we do not want to
    # bother with incompatibilities in our nightly builds.
    - {{ pin_subpackage(name, exact=True) }}
{%- endif %}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
{%- if target == "benchmark" %}
    - git
{%- elif target == "style" %}
    - clangdev ==8.0.0
{%- endif %}
  host:
{%- if name in ["flatsurf", "libflatsurf"] %}
    - arb
    - boost-cpp
    - libintervalxt
    - libexactreal
    - e-antic 1.*
    - gmp
{%- endif %}
{%- if name in ["flatsurf", "pyflatsurf"] %}
    - python
    - setuptools
    - pyexactreal
{%- endif %}
{%- if name in ["flatsurf", "flatsurf-polygon"] %}
    - arb
    - boost-cpp
    - libexactreal
    - libintervalxt
    - e-antic 1.*
    - gmp
    - ntl
    - eigen
{%- endif %}
{%- if name in ["pyflatsurf", "flatsurf-polygon"] %}
    - libflatsurf {{ version }} {{ build_number }}
{%- endif %}
{%- if target in ["test", "coverage", "benchmark"] %}
    # enable test/pyflatsurf tests in ./configure
    - pytest
    - cppyy
    # make sage-flatsurf integration doctests pass
    - sage-flatsurf
    - sagelib
    - pip
    - ipywidgets
    - sympy
    # enable test/libflatsurf tests in ./configure
    - gtest
    - benchmark
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0
{%- endif %}
{%- if target == "benchmark" %}
    # requirements for ASV benchmarks
    - asv
{%- endif %}
  run:
{%- if name == "pyflatsurf" %}
    - python
    - cppyy
    - pyexactreal
    - boost-cpp
{%- endif %}

outputs:
  - name: {{ name }}
{%- if target == "release" %}
    script: install-{{ name }}.sh
{%- endif %}
{%- if name == "pyflatsurf" %}
    test:
      imports:
        - {{ name }}
{%- endif %}
{%- if name == "flatsurf-polygon" %}
    test:
      commands:
        - flatsurf-polygon 1 2 2 1
{%- endif %}

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL3
  license_file: COPYING
  summary: TBD

extra:
  recipe-maintainers:
    - saraedum
    - videlec
