# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + ((build_flavour + "_") if build_flavour != "release" else "") + build_number %}

package:
  name: flatsurf
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # intervalxt is not available on Windows yet
  skip: True  # [win]
  # intervalxt is not available on macOS yet
  skip: True  # [osx]

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - {{ compiler('cxx') }}
    # requirements for ASV benchmarks
    - git
    # requirements for clang-format
    - clangdev ==8.0.0
  host:
    # compile time dependencies of libflatsurf
    - boost-cpp
    - libintervalxt
    - libexactreal
    - pyexactreal
    - e-antic 1.*
    - gmp
    # compile time dependencies of flatsurf-polygon
    - ntl
    - eigen
    # We pin to an explicit version of Python here; since the Python part is
    # noarch:python, the version does not matter. However, we need the same
    # version when doing "make install" so that files go into the site-packages
    # directory that was determined by ./configure.
    - python =3.7
    # enable test/pyflatsurf tests in ./configure
    - pytest
    - cppyy
    # make sage-flatsurf integration doctests pass
    - sage-flatsurf
    # enable test/libflatsurf tests in ./configure
    - gtest
    - benchmark
    # enable check-valgrind in ./configure
    - valgrind
    # requirements for ASV benchmarks
    - asv

outputs:
  - name: libflatsurf
    script: install-libflatsurf.sh
    build:
      number: {{ build_number }}
      string: {{ build_string }}
{%- if build_flavour and build_flavour != 'release' %}
      features:
        - {{ build_flavour }}
{% endif %}
    requirements:
      build:
        - libtool
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - libintervalxt
        - libexactreal
        - e-antic 1.*
        - gmp
    run_exports:
      # We pin the version of libflatsurf exactly since we do not want to
      # bother with incompatibilities in our nightly builds.
      - libflatsurf {{ version }}
  - name: flatsurf-polygon
    script: install-flatsurf-polygon.sh
    build:
      number: {{ build_number }}
      string: {{ build_string }}
{%- if build_flavour and build_flavour != 'release' %}
      features:
        - {{ build_flavour }}
{% endif %}
    requirements:
      build:
        - libtool
        - {{ compiler('cxx') }}
      host:
        - boost-cpp
        - libintervalxt
        - libexactreal
        - e-antic 1.*
        - gmp
        - eigen
        - ntl
      run:
        # We pin the version of libflatsurf exactly since we do not want to
        # bother with incompatibilities in our nightly builds.
        - {{ pin_subpackage('libflatsurf', exact=True) }}
{%- if build_flavour == 'release' %}
    test:
      commands:
        - flatsurf-polygon 1 2 2 1
{% endif %}
  - name: pyflatsurf
    build:
      number: {{ build_number }}
      string: {{ build_string }}
{%- if build_flavour and build_flavour != 'release' %}
      features:
        - {{ build_flavour }}
{% endif %}
      noarch: python
    script: install-pyflatsurf.sh
    requirements:
      host:
        - python =3.7
        - setuptools
      run:
        - python
        # We pin the version of libflatsurf exactly since we do not want to
        # bother with incompatibilities in our nightly builds.
        - {{ pin_subpackage('libflatsurf', exact=True) }}
        - cppyy
        - pyeantic
        - pyintervalxt
        - pyexactreal
        - boost-cpp
{%- if build_flavour == 'release' %}
    test:
      imports:
        - pyflatsurf
{% endif %}

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL3
  license_file: COPYING
  summary: TBD

extra:
  recipe-maintainers:
    - saraedum
    - videlec
