{% set name = "polygon" %}

package:
  name: {{ name }}
  version: "{{ environ.get('GIT_DESCRIBE_TAG') }}"

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

# TODO: run_exports & split outputs once this is a library

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER') }}
  string: master
  skip: true        # [win or osx]

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - gmp
    - ntl
    - boost-cpp

test:
  source_files:
    - test/
  commands:
    - test/run.sh

about:
  home: https://github.com/polygon-tbd/polygon
  license: GPL2
  license_file: COPYING
  summary: Alex Eskin's polygon program

extra:
  recipe-maintainers:
    - saraedum
