language: generic
  
os:
  - linux

env:
  global:
    - MAKEFLAGS=-j2

branches:
  only:
    - master

before_install:
  # Install Miniconda.
  - |
    MINICONDA_URL="https://repo.continuum.io/miniconda"
    if [ $TRAVIS_OS_NAME = linux ]; then
        MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
    elif [ $TRAVIS_OS_NAME = osx ]; then
        MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
    fi
    curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
    bash $MINICONDA_FILE -b

  # Configure conda.
  - |
    source $HOME/miniconda3/bin/activate root
    conda config --add channels conda-forge
    conda config --set show_channel_urls true
    conda update --all --yes
    conda info

  # Setup conda build environment.
  - conda install --yes conda-build conda-verify

install:
  - conda build --error-overdepending --error-overlinking recipe
  - conda install --yes -c local polygon

jobs:
  include:
    - name: distcheck
      install:
        # distcheck.sh drops us into a configured environment
        # like the one that conda build uses internally
        - conda debug -a recipe > distcheck.sh
      script: 
        - |
          cat >> distcheck.sh <<EOF
          ./bootstrap
          ./configure
          make distcheck
          EOF
        - bash distcheck.sh
    - name: test
      script: test/run.sh
    - name: coverage
      env:
        - secure: aKAE28aynidhLqPuX5vDQ7wvDo2Fpx+aLefatuN0BDWi7lOIuhqOv/6LOT/pkDivNmUuaoRuhUi6eFcCgX110EhyIW7kUzk6Ijmq0EJMtwj/Gm69pu+6AcLfu6E7UkyBNoknh1EKG/Bs9TWt5oL1nDsuDcV1rTW18+EoRXNDXonPLuwFnFrZHUZkQLpU9BTp28VettYhs+Qx4RVbtddau1cs4uiu0VOswvFv8zMTgOVXCb/mADz9Lrs/h7dHc7yetVH4JT1n98Kp8b3fU/+zLJXyck8xx7TM7ZGdGexA59swC3dqrDv0vnKgBPbKLnMMGdmHN0Q0d/boCE9NTOmOoU7SCTpDomwRYmED/k/nDPKANTlPyBJOvEtRfm5hgbuMvMWL4m1q8ojEsb2CTZtUXKLE2+4ltCIInDfk2S8xlywGcaEMqUMY72r4ARkgUyQR95PubX63F0Dd+fU+KhpQBFOH3WNyeBZPio/aG6t8RzU7jzOFccp/lnj2L9Ff2P8L5ZBQEkEUDdREcEyIAyAfSTde7LAEgpfAJm0m9O7Sek96H0ClANc02n+fHiH8iJn5XXViL5gorSr/T+yxdQkLWGjOjri75timw5oFdHSn8eiulhQqkuWoRTgxEQoY9O5bLrM0zE2kK2IVgeGQ4rtOjUWGQxFYrY0jszi8ZXg4rDA=
      os: linux
      install:
        - export EXTRA_CXXFLAGS="--coverage"
        - conda build --keep-old-work --no-remove-work-dir --old-build-string --dirty recipe
        - conda install --yes -c local polygon
      script:
        - pip install --user pyyaml cpp-coveralls
        - cd /home/travis/miniconda3/conda-bld/polygon*/work
        - test/run.sh
        - coveralls
