# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kG/7Z9dIxxmyeVeOwYs7+CkTXfDIqXtMbon66h99hAP/JSOBrNNGTPEN5/t6bL8gfyfivSojQMG5LWEbdRNbzJCdoWZtu8+eOqxNKXcOXDYaB8ajlYctS0gHjaqLcjSSwu2svFJOgdBDCETkdFYvg9jaNutQybOlWq42K+RiAvAFNGGAo8RLxLhYgbGZpVYqTggVcby8uIS6rxiC2KYR2+2+niJTI2y2Jo7Rqdgp5XBWpWrDod8Yns8idUgjPbll09fD4DyY1OYZlhMmhSCFcAGLjHQsCiGq3FGk3jPs3QaMC9w71U7xijdXpR4yUAuBHIEZCFrcTM5eRn+d2bbJX4rdoAGCUOvRSLPaP5WYYzyi30+wmwpArC4ZHjMDPaPPJ6yxQroJeiBZAfWe8L5FLwq0jxkH1w+EE2a3q1U6bzyePy85VQu4i42cLCNqfksJDAaR6sXcMpko15fOIX+lbqoPjvoE+3NhbqIpSEaCoxm3Hd/TQMqDw/CRn9pYRviVXfF7ofyGtXlEyIne8IrcgV66+fyxfEw+vNhqrRxchh4aOZzreJ7hxfSIxZvstW9K8oRoz4W+H896EL3WUGu40Dc2LbEytXyc0Dl8HdZsbEYm1xdzVM4aHUZ879ElbiiLy5PzWPoSUCschuvrUe24IJiQJ5wuMB6XaTl6Ry38uQs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml