# This environment.yml can be used to create a conda environment with
# pyflatsurf/libflatsurf installed. It is used for our demo binders.
name: binder
channels:
  - conda-forge
  - defaults
dependencies:
  - libflatsurf>=3.0.0
  - notebook
  - pyflatsurf>=3.0.0
  - sage-flatsurf
  - sagelib
  - xeus-cling
