{% set version = '3.10.1' %}
{% set build_number = '0' %}

package:
  name: libflatsurf
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # libeantic is not available on Windows yet
  skip: True  # [win]
  run_exports:
  - {{ pin_subpackage("libflatsurf", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - arb {{ arb }}
    - boost-cpp {{ boost_cpp }}
    - libintervalxt >=3.1.3,<4
    - libexactreal >=2.2.1,<3
    - libflint {{ libflint }}
    - libeantic >=1.0.0,<2
    - gmp {{ gmp }}
    - gmpxxll
    - fmt {{ fmt }}

test:
  commands:
    - test -f ${PREFIX}/lib/libflatsurf.so

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: TBD

