name: binder
channels:
  - saraedum
  - conda-forge
  - defaults
  - conda-forge/label/broken
dependencies:
  - polygon
  - boost-cpp
  - xeus-cling=0.4.10
  - xtensor=0.19.0
  - xtensor-blas=0.15.0
  - notebook
  - xtl=0.5.2
