name: binder
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - libflatsurf
  - pyflatsurf
  - flatsurf-polygon
  - sage-flatsurf
  - boost-cpp
  - notebook
  - sagelib
  # https://github.com/QuantStack/xeus-cling/issues/194#issuecomment-456547091
  - xeus-cling
