# Pins from https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml
# so our packages is compatible with the choices made by conda-forge.
python:
  - 3.6.* *_cpython    # [not (osx and arm64)]
  - 3.7.* *_cpython    # [not (osx and arm64)]
  # pyeantic does not build against Python 3.8 yet
  # - 3.8.* *_cpython
