{% set version = '3.13.1' %}
{% set build_number = '0' %}

package:
  name: pyflatsurf
  version: {{ version }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # libflatsurf is not available on Windows yet
  skip: True  # [win]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
    - make
  host:
    - python
    - setuptools
    - gmpxxyy >=1.0.1,<2
    - pyexactreal >=3.0.1,<4
    - cppyythonizations
    - libflatsurf
  run:
    - python
    - cppyy >=2.1.0,<3
    - cppyythonizations
    - pyexactreal >=3.0.1,<4
    - boost-cpp

test:
  imports:
    - pyflatsurf

about:
  home: https://github.com/flatsurf/flatsurf
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: TBD
