# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      benchmark:
        CONFIG: linux_benchmark
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      coverage:
        CONFIG: linux_coverage
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      release:
        CONFIG: linux_release
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      style:
        CONFIG: linux_style
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      test36:
        CONFIG: linux_test36
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      test37:
        CONFIG: linux_test37
        UPLOAD_PACKAGES: 'False'
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
    maxParallel: 8
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      ASV_SECRET_KEY: $(ASV_SECRET_KEY)
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      CODECOV_TOKEN: $(CODECOV_TOKEN)