# This file lists the dependencies needed to build and test all of libflatsurf.
# # Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: libflatsurf-build
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - automake
  - benchmark
  - boost-cpp
  - coreutils
  - cxx-compiler>=1.1.3
  - e-antic>=1.0.0rc11,<2
  - fmt=7
  - gmp=6
  - gmpxxll>=1.0.0,<2
  - libexactreal>=1.4.3,<2
  - libintervalxt>=3.0.2,<4
  - libtool
  # valgrind is only needed for make check-valgrind
  # - valgrind
