# This file lists the dependencies needed to build and test all of libflatsurf.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
name: libflatsurf-build
channels:
  - conda-forge
  - defaults
dependencies:
  - automake
  - benchmark
  - boost-headers=1.82.0
  - coreutils
  - cxx-compiler
  - libeantic>=2,<3
  - libflint>=3,<4
  - fmt=10
  - gmp=6
  - gmpxxll>=1.0.0,<2
  - libexactreal>=4,<5
  - libintervalxt>=3.0.2,<4
  - libtool
  - make
  - parallel
  # valgrind is only needed for make check-valgrind
  # - valgrind
