name: Developer Tasks
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.on }}
    strategy:
      matrix:
        on: ["ubuntu-24.04"]
    steps:
    - uses: actions/checkout@v5
      with: { submodules: recursive }
    - uses: prefix-dev/setup-pixi@v0.9.1
      with: { pixi-version: v0.53.0 }
    - run: pixi run build
    - run: pixi run compile-commands
    - run: pixi run sage -c 'import pyflatsurf'
    - run: pixi run clean

