name: Code Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.11
      with:
        source: libflatsurf
        clangFormatVersion: 10
        extensions: cc,hpp,ipp,h,h.in,hpp.in
        inplace: true
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: clang-format bot
        author_email: bot@flatsurf.org
        message: 'clang-format source code'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
